import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
import {mkdirSync} from 'node:fs';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const browser=await chromium.launch({headless:true,channel:'chrome'});
const context=await browser.newContext({viewport:{width:1440,height:1050}});
const page=await context.newPage();
const errors=[];page.on('pageerror',e=>errors.push(e.message));
mkdirSync('.sites-runtime/qa',{recursive:true});
const origin='http://localhost:5173';
await page.goto(origin+'/signin-with-chatgpt?return_to=%2F');
await page.locator('.knowledge-card').first().waitFor();
const baselineCards=(await (await context.request.get(origin+'/api/cards')).json()).cards;
assert.equal(await page.locator('.knowledge-card').count(),baselineCards.length);
await page.screenshot({path:'.sites-runtime/qa/desktop.png',fullPage:true});
await page.getByRole('textbox',{name:'搜索知识'}).fill('MPV');
assert((await page.locator('.knowledge-card').count())>=1);
await page.getByRole('textbox',{name:'搜索知识'}).fill('');
await page.getByRole('button',{name:'随手记',exact:true}).click();
await page.getByLabel('中文 / 随手记').fill('测试知识卡（自动验证）');
await page.getByLabel('English',{exact:true}).fill('Test knowledge');
await page.getByLabel('一句话理解').fill('测试保存和多端刷新。');
await page.getByRole('button',{name:'保存知识卡',exact:true}).click();
await page.getByRole('dialog',{name:'记下一个新发现'}).waitFor({state:'hidden'});
await page.getByRole('dialog',{name:'测试知识卡（自动验证）'}).waitFor();
await page.keyboard.press('Escape');
assert.equal(await page.locator('.knowledge-card').count(),baselineCards.length+1);
await page.reload();await page.locator('.knowledge-card').first().waitFor();
assert.equal(await page.locator('.knowledge-card').count(),baselineCards.length+1);
await page.getByRole('button',{name:/测试知识卡（自动验证）/}).click();
await page.getByRole('button',{name:'编辑知识卡',exact:true}).click();
await page.getByLabel('一句话理解').fill('内容已编辑并持久保存。');
await page.getByRole('button',{name:'保存知识卡',exact:true}).click();
await page.getByText('内容已编辑并持久保存。',{exact:true}).waitFor();
await page.keyboard.press('Escape');
const data=await context.request.get(origin+'/api/cards');const snapshot=await data.json();const card=snapshot.cards.find(c=>c.zh==='测试知识卡（自动验证）');assert(card);
const review={id:crypto.randomUUID(),cardId:card.id,version:card.version,correct:false,mode:'exam',response:'测试答案'};
const first=await context.request.post(origin+'/api/reviews',{data:review});assert.equal(first.status(),200,await first.text());
const retry=await context.request.post(origin+'/api/reviews',{data:review});assert.equal(retry.status(),200);assert.equal((await retry.json()).card.wrong,1);
const conflict=await context.request.put(origin+'/api/cards',{data:{id:card.id,version:card.version,content:card}});assert.equal(conflict.status(),409);
await page.reload();await page.locator('.knowledge-card').first().waitFor();
await page.locator('.side').getByRole('button',{name:/错题本/}).click();
assert.equal(await page.locator('.knowledge-card').count(),baselineCards.filter(c=>c.lastResult==='wrong').length+1);
await page.locator('.side').getByRole('button',{name:'随机考试',exact:true}).click();
await page.getByRole('button',{name:'开始随机考试',exact:true}).click();
await page.getByLabel('我的答案').fill('我的回答');await page.getByRole('button',{name:'查看参考答案',exact:true}).click();
await page.getByRole('button',{name:'记住了 · Correct',exact:true}).click();await page.getByText(/已保存 · 下次复习/).waitFor();
await page.getByRole('button',{name:'结束本轮',exact:true}).click();
const updated=(await (await context.request.get(origin+'/api/cards')).json()).cards.find(c=>c.id===card.id);
assert.equal((await context.request.delete(origin+'/api/cards',{data:{id:card.id,version:updated.version}})).status(),200);
await page.setViewportSize({width:390,height:844});await page.reload();await page.locator('.knowledge-card').first().waitFor();
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
assert.equal(await page.locator('.mobile-nav').isVisible(),true);
await page.screenshot({path:'.sites-runtime/qa/mobile.png',fullPage:true});
await page.getByRole('button',{name:'随手记',exact:true}).click();await page.getByLabel('中文 / 随手记').fill('草稿保留测试');await page.keyboard.press('Escape');
await page.getByRole('button',{name:'随手记',exact:true}).click();assert.equal(await page.getByLabel('中文 / 随手记').inputValue(),'草稿保留测试');await page.keyboard.press('Escape');
await page.evaluate(()=>{for(const key of Object.keys(localStorage))if(key.startsWith('industry-draft:'))localStorage.removeItem(key)});
const manifest=await (await context.request.get(origin+'/manifest.webmanifest')).json();assert.equal(manifest.display,'standalone');
await page.evaluate(()=>navigator.serviceWorker.ready);
await context.setOffline(true);await page.reload();await page.getByText('连接恢复后，继续学习。').waitFor();await context.setOffline(false);
assert.equal(errors.length,0,errors.join('\n'));
const anonymous=await browser.newContext();const unauthorized=await anonymous.request.get(origin+'/api/cards');assert.equal(unauthorized.status(),401);
console.log('PASS: desktop/mobile CRUD, persistence, review idempotency, edit conflict, exam, wrong list, drafts, PWA offline, anonymous denial.');
await browser.close();
