import assert from 'node:assert/strict';
import {schedule,DAY,weight,reviewQueue,examQueue} from '../lib/scheduling';
import {blankContent,quickEntrySeed,type Card} from '../lib/knowledge';
import {contentSchema,updateSchema} from '../lib/validation';
const now=1700000000000;
const base:Card={...blankContent,id:'test',zh:'测试',explanation:'定义',createdAt:now-30*DAY,updatedAt:now,correct:0,wrong:0,streak:0,lastReview:null,nextReview:now,lastResult:null,version:1};
assert.equal(schedule(base,true,now).nextReview,now+DAY);
assert.equal(schedule({...base,streak:2},true,now).nextReview,now+7*DAY);
assert.equal(schedule({...base,streak:100},true,now).nextReview,now+90*DAY);
assert.deepEqual(schedule({...base,streak:4},false,now),{streak:0,nextReview:now+600000,lastReview:now,lastResult:'wrong'});
assert(weight({...base,lastResult:'wrong'},now)>weight(base,now));
assert(weight({...base,createdAt:now},now)>weight(base,now));
assert(weight(base,now)>weight({...base,nextReview:now+DAY},now));
assert.deepEqual(reviewQueue([base,{...base,id:'future',nextReview:now+DAY},{...base,id:'draft',explanation:''}],now).map(x=>x.id),['test']);
assert.equal(examQueue([base,{...base,id:'2'},{...base,id:'draft',explanation:''}],10,()=>.5,now).length,2);
assert.equal(new Set(examQueue([base,{...base,id:'2'}],10).map(c=>c.id)).size,2);
assert(contentSchema.safeParse({...blankContent,zh:'随手记'}).success);
assert(!contentSchema.safeParse(blankContent).success);
assert(!contentSchema.safeParse({...blankContent,zh:'坏图片',image:'javascript:alert(1)'}).success);
assert(updateSchema.safeParse({id:'seed-1',version:1,content:{...blankContent,zh:'捷途'}}).success);
const mpv=quickEntrySeed({...blankContent,zh:'MPV'});
assert.equal(mpv?.en,'Multi-Purpose Vehicle');
assert.equal(mpv?.zh,'多用途汽车');
assert.equal(quickEntrySeed({...blankContent,zh:'honda crv'})?.en,'Honda CR-V');
assert.equal(quickEntrySeed({...blankContent,zh:'未知术语'}),undefined);
assert.equal(quickEntrySeed({...blankContent,zh:'MPV',explanation:'我的自定义解释'}),undefined);
assert.equal(reviewQueue([{...base,...mpv}],now+DAY).length,1);
assert.equal(reviewQueue([{...base,...mpv,...schedule(base,true,now)}],now+DAY).length,1);
console.log('PASS: 21 scheduling, queue, quick-entry and validation checks');
