'use client';
import {useState} from 'react';
import Image from 'next/image';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {AlertDialog,AlertDialogTrigger,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogCancel,AlertDialogAction,AlertDialogFooter} from '@/components/ui/alert-dialog';
import {Progress} from '@/components/ui/progress';
import {Volume2,Pencil,Trash2,ExternalLink} from 'lucide-react';
import {mastery,status,isLearnable,type Card} from '@/lib/knowledge';
import {api} from '@/lib/client';
export function date(value:number|null){return value?new Date(value).toLocaleString('zh-CN',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):'尚未复习'}
export function speak(text:string){if(!('speechSynthesis' in window))return false;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=.8;speechSynthesis.speak(u);return true}
export default function CardDetail({card,onClose,onEdit,onDelete,onRelated}:{card:Card;onClose:()=>void;onEdit:()=>void;onDelete:(id:string)=>void;onRelated:(s:string)=>void}){
 const [error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function remove(){setBusy(true);try{await api('/api/cards',{method:'DELETE',body:JSON.stringify({id:card.id,version:card.version})});onDelete(card.id)}catch(e){setError(e instanceof Error?e.message:'删除失败')}finally{setBusy(false)}}
 return <Sheet open onOpenChange={v=>{if(!v&&!busy)onClose()}}><SheetContent className="detail-sheet"><div className="detail-head"><span className="badge">{card.category}</span><SheetTitle className="detail-title">{card.zh||card.en}</SheetTitle><SheetDescription className="detail-english">{card.en}{card.abbreviation&&card.abbreviation!==card.en?` · ${card.abbreviation}`:''}</SheetDescription><div className="tag-list">{card.tags.map(t=><button className="chip" key={t} onClick={()=>onRelated(t)}>#{t}</button>)}</div></div><div className="detail-body"><div className="pronunciation"><div><strong>读一读</strong><button className="text-button" onClick={()=>{if(!speak(card.en||card.abbreviation))setError('这个浏览器暂不支持朗读，可参考音标练习')}} disabled={!card.en&&!card.abbreviation}><Volume2 size={16}/> 慢速朗读</button></div>{card.ipa&&<p className="ipa">{card.ipa}</p>}<p>{card.pronunciation||'发音提示待补充'}</p><small>浏览器合成语音仅辅助练习，品牌读音以官方为准。</small></div>{[['一句话理解',card.explanation],['业务场景',card.scenario],['中英文表达',card.example],['考点',card.question],['参考答案',card.answer]].map(([label,value])=><section className="detail-section" key={label}><h3>{label}</h3><p>{value||'待补充'}</p></section>)}{card.image&&<Image unoptimized width={800} height={500} className="card-image" src={card.image} alt={`${card.zh}参考图片`} referrerPolicy="no-referrer" onError={e=>{e.currentTarget.alt='图片暂时无法加载，请检查链接'}}/>}<section className="detail-section"><h3>关联知识</h3><div className="tag-list">{card.related.length?card.related.map(s=><button key={s} className="chip" onClick={()=>onRelated(s)}>{s} ↗</button>):<p>待补充</p>}</div></section>{card.source&&<a className="source-link" href={card.source} target="_blank" rel="noreferrer"><ExternalLink size={14}/> 查看参考来源</a>}<div className="mastery-panel"><div><strong>{isLearnable(card)?status(card):'待完善'}</strong><span>掌握度 {mastery(card)}%</span></div><Progress value={mastery(card)} aria-label="掌握度"/><small>连续答对 3 次记为已掌握；答错重新巩固。</small><dl><div><dt>Correct / 答对</dt><dd>{card.correct}</dd></div><div><dt>Wrong / 答错</dt><dd>{card.wrong}</dd></div><div><dt>Last Review</dt><dd>{date(card.lastReview)}</dd></div><div><dt>Next Review</dt><dd>{isLearnable(card)?date(card.nextReview):'完善后加入复习'}</dd></div></dl></div>{error&&<p role="alert" className="error-message">{error}</p>}</div><div className="detail-actions"><button className="primary" onClick={onEdit}><Pencil size={16}/> 编辑知识卡</button><AlertDialog><AlertDialogTrigger asChild><button className="quiet-button" aria-label="删除知识卡"><Trash2 size={17}/></button></AlertDialogTrigger><AlertDialogContent><AlertDialogTitle>删除这张知识卡？</AlertDialogTitle><AlertDialogDescription>卡片及其掌握度将从所有设备的知识库移除。</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>保留</AlertDialogCancel><AlertDialogAction onClick={remove} disabled={busy}>删除</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div></SheetContent></Sheet>
}
