'use client';
import {useState,useEffect} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {blankContent,categories,quickEntrySeed,type Card,type Content} from '@/lib/knowledge';
import {api} from '@/lib/client';
import {Plus,Save,ChevronDown} from 'lucide-react';
export default function CardEditor({card,account,onClose,onSave}:{card:Card|null;account:string;onClose:()=>void;onSave:(c:Card)=>void}){
 const key=`industry-draft:${account}`;
 const [content,setContent]=useState<Content>(()=>{if(card)return card;try{return {...blankContent,...JSON.parse(localStorage.getItem(key)||'{}')}}catch{return {...blankContent}}});
 const [id]=useState(()=>card?.id||crypto.randomUUID());
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 const [tags,setTags]=useState(content.tags.join(', ')),[related,setRelated]=useState(content.related.join(', '));
 useEffect(()=>{if(!card)try{localStorage.setItem(key,JSON.stringify({...content,tags:tags.split(/[,，]/).map(s=>s.trim()).filter(Boolean),related:related.split(/[,，]/).map(s=>s.trim()).filter(Boolean)}))}catch{}},[card,key,content,tags,related]);
 const known = !card ? quickEntrySeed(content) : undefined;
 function change(k:keyof Content,v:string){setContent(c=>({...c,[k]:v}))}
 async function save(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const c={...content,tags:tags.split(/[,，]/).map(s=>s.trim()).filter(Boolean),related:related.split(/[,，]/).map(s=>s.trim()).filter(Boolean)};const data=await api<{card:Card}>('/api/cards',{method:card?'PUT':'POST',body:JSON.stringify({id,content:c,version:card?.version})});if(!card)try{localStorage.removeItem(key)}catch{}onSave(data.card)}catch(e){setError(e instanceof Error?e.message:'保存失败，请重试')}finally{setBusy(false)}}
 const field=(k:keyof Content,label:string,placeholder='',area=false)=><label className="field" key={k}><span>{label}</span>{area?<textarea value={content[k] as string} onChange={e=>change(k,e.target.value)} placeholder={placeholder} maxLength={6000} rows={3}/>:<input value={content[k] as string} onChange={e=>change(k,e.target.value)} placeholder={placeholder} maxLength={['image','source'].includes(k)?2000:300}/>}</label>;
 return <Dialog open onOpenChange={v=>{if(!v&&!busy)onClose()}}><DialogContent className="editor-dialog"><DialogTitle>{card?'编辑知识卡':'记下一个新发现'}</DialogTitle><DialogDescription>{card?'补充解释、发音和业务场景。':'输入一个词即可保存；已预置的术语会直接打开完整知识卡。'}</DialogDescription><form onSubmit={save} className="editor-form"><div className="field-grid">{field('zh','中文 / 随手记','例如：今天遇到 wheelbase，不太懂')}{field('en','English','例如：Wheelbase')}</div><div className="field-grid"><label className="field"><span>一级分类</span><Select value={content.category} onValueChange={v=>change('category',v)}><SelectTrigger aria-label="一级分类"><SelectValue/></SelectTrigger><SelectContent>{categories.map(c=><SelectItem key={c} value={c}>{c}</SelectItem>)}</SelectContent></Select></label><label className="field"><span>标签 · 逗号分隔</span><input value={tags} onChange={e=>setTags(e.target.value)} placeholder="Automotive English"/></label></div>{known&&<p className="quick-entry-hint">已匹配：{known.abbreviation||known.en} · {known.zh}。保存后可直接学习和复习。</p>}{field('explanation','一句话理解','用自己的话解释它是什么',true)}<details open={Boolean(card)}><summary><Plus size={15}/> 补充完整知识卡 <ChevronDown size={15}/></summary><div className="field-grid">{field('abbreviation','缩写','例如：MPV')}{field('ipa','IPA 音标','例如：/ˈpɪk.ʌp/')}</div>{field('pronunciation','发音提示','重音在哪里？逐字母读还是作为一个词读？',true)}{field('scenario','业务场景','什么时候会用到？',true)}{field('example','中英文例子','写一句客户沟通中可以用的表达',true)}{field('question','考点 / 问题','未来想考自己什么？',true)}{field('answer','参考答案','没有单独答案时，复习会使用简明解释',true)}<label className="field"><span>关联知识 · 逗号分隔</span><input value={related} onChange={e=>setRelated(e.target.value)} placeholder="Honda, Honda CR-V"/></label>{field('image','图片链接（可选）','https://…')}{field('source','来源链接（可选）','https://…')}</details>{error&&<p role="alert" className="error-message">{error}</p>}<div className="form-footer"><small>{card?'保存后同步到当前账户':'输入内容暂存在本机草稿，保存后进入账户知识库'}</small><button className="primary" disabled={busy||!(content.zh.trim()||content.en.trim())}><Save size={16}/>{busy?'正在保存…':'保存知识卡'}</button></div></form></DialogContent></Dialog>
}
